classDiagram
    Meeresbewohner <|-- Raubfisch : ist ein
    Raubfisch <|-- HeyFisch : ist ein
    Person <|-- KITAngestellter : ist ein
    KITAngestellter <|-- TobiasHey : ist ein
    WalterFTichy <-- TobiasHey : arbeitet für
    Professor <|-- WalterFTichy : ist ein
    KITAngestellter *-- Professor : ist ein
    TobiasHey o-- HeyFisch : gehört
    WalterFTichy : void singen()
    WalterFTichy : String Willkommen
    WalterFTichy <--> RCS : Entwickler