name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: main.tex
          latexmk_shell_escape: true
          #post_compile: "latexmk -c && mv main.pdf ./builds/$(date \"+%D-%T\").pdf"
          post_compile: "latexmk -c && mv ./main.pdf ./builds/$(date \"+%D-%T\").pdf"
